apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weahter-app
  namespace: argocd 
spec:
  destination: 
    namespace: dayo777
    server: https://kubernetes.default.svc 
  project: default 
  source:
    repoURL: https://github.com/dayo777/gitops-argocd.git
    path: deployment
    targetRevision: main